### ISSUE TITLE
[Question] Is it possible to have relationships display the uri when posing a get request?

### ISSUE THREAD

**Issue by AnnemarieWittig** [mu-semtech/mu-cl-resources#18]
Hello!
Is it possible to adjust the domain.lisp to show a URI for the relationships of an object when sending a get request - similar to the ":features '(include-URI)" tag? So that, as an example, instead of having this as part of my returned value:
``` 
"relationships": {   
                "City": {   
                    "links": {   
                        "self": "/Addresses/5FF81693385241000900000E/links/City?filter[City][name]=UnknownCity",   
                        "related": "/Addresses/5FF81693385241000900000E/City"  
                    }   
                }   
            }   
```
I could get:
```
 "relationships": {
                "City": {
                    "URI": "some kind of URI",
                    "links": {
                        "self": "/Addresses/5FF81693385241000900000E/links/City?filter[City][name]=UnknownCity",
                        "related": "/Addresses/5FF81693385241000900000E/City"
                    }
                }
            }
```

**Comment by madnificent** [comment]
Hi!  Thank you for your interest in this project.  I totally didn't see this issue pop in.

I can interpret the question in two slightly different ways.

Likely, you're interested in getting the URI of the related resource.  In such case, you can use the feature you described and also use a `?include=city`.  This will add the related resource to the response.

You might be interested in adding the predicate of the followed relationship in the relationships object, so we expose that in a similar way to the `include-uri` feature.  I think we could add something along those lines.  It might not be possible for all relationships.  The biggest hurdle would be getting this compliant with jsonapi.org.  If you'd find the time see how this would integrate in a valid jsonapi compliant response we can probably take this further.

Perhaps an alternative and interesting direction is to see if we can marry json-api and json-ld, in which case the replied response could be consumed as Linked Data directly.
