### ISSUE TITLE
Number of results

### ISSUE THREAD

**Issue by lordblendi** [mu-semtech/mu-cl-resources#3]
Hey @madnificent !

It would be nice to have the number of results in the response. Because of the pagination, I cannot count them on front end side.

Thanks!

**Comment by nvdk** [comment]
I'm against including this (or at least being able to disable it), for large databases counting all resources is an operation that will time out.

**Comment by madnificent** [comment]
@lordblendi As per 5b636d5f02f01cb632c5e649da2855ee12b45157 you can either use the optional feature `include-count` (advised b/c experimental) on a per-resource basis, or enable it globally by pasting the following snippet in your domain.lisp:

    (setf  *include-count-in-paginated-responses*)

For the record: @nvdk, as discussed on chat, we always have to run the count query for the links object.  Disabling the links object (and therefore running the count) will be a separate issue.
